POST https://api.github.com/repos/jesadato/git-action-demo/dispatches
Content-Type: application/json
Accept: application/vnd.github+json
Authorization: Bearer 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

{
  "event_type": "on-demand-test",
  "client_payload": {
    "status": "completed"
    }
}

