POST https://api.github.com/repos/jesadato/git-action-demo/dispatches
Content-Type: application/json
Accept: application/vnd.github+json
Authorization: Bearer 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

{
  "event_type": "on-demand-test",
  "client_payload": {
    "status": "completed"
    }
}
