name : workflow for feature Branch
on:
   push:
     branches: [feature/**]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check new feature quality
        run: echo "Start unit testing"
   seccond-job:
     runs-on: windows-latest
     needs: hello-job
     steps:
        - run: echo "This job is running on ${{runner.os}}"
